hotpotato/views/notifications/forms.py
from flask_wtf import FlaskForm


class AcknowledgeForm(FlaskForm):
    pass

hotpotato/api/web/v1/notifications/__init__.py
"""
Web API version 1 notification endpoints.
"""


from hotpotato.api.web.v1.notifications import get  # noqa: F401

hotpotato/api/web/v1/notifications/handlers/__init__.py
"""
Web API version 1 notification handler functions.
"""


from http import HTTPStatus

from hotpotato.api.web.v1.notifications import (
    exceptions as api_web_notifications_exceptions,
)
from hotpotato.api.web.v1.notifications.handlers import (
    alerts as handler_alerts,
    handovers as handler_handovers,
    messages as handler_messages,
    notifications as handler_notifications,
)

_notif_handlers = {
    "notifications": handler_notifications,
    "alerts": handler_alerts,
    "handovers": handler_handovers,
    "messages": handler_messages,
}


def get(handler_name):
    """
    Return the notification handler for the given handler name.
    """

    if handler_name not in _notif_handlers:
        raise api_web_notifications_exceptions.APIWebV1NotificationHandlerError(
            "Invalid notification handler type: {}".format(handler_name),
            success=False,
            code=HTTPStatus.BAD_REQUEST,
        )

    return _notif_handlers[handler_name]

hotpotato/notifications/__init__.py
"""
Notification constants and helper classes.
"""


import types

JSON_VERSION = 1


# A frozen set of values representing the type of a notification.
# NOTE: This list referenced by the Hot Potato database. If it is changed,
#       a new database migration will need to be created.
TYPE = frozenset(("alert", "handover", "message"))


# A frozen set of values representing the status of a notification.
STATUS = frozenset(
    (
        "NEW",
        "UNSENT",
        "SEND_FAILED",
        "SEND_FAILED_ACKNOWLEDGED",
        "SENDING",
        "SENT_TO_PROVIDER",
        "RECEIVED_BY_PROVIDER",
        "SENT_TO_CLIENT",
        "RECEIVED_BY_CLIENT",
        "READ_BY_CLIENT",
    )
)


# A frozen set of values representing verifiable sending methods.
VERIFIABLE_METHOD = frozenset(("app", "pushover"))

# A frozen set of values representing unverifiable sending methods.
UNVERIFIABLE_METHOD = frozenset(("pager", "sms"))

# A frozen set of values representing all possible sending methods for a notification.
METHOD = VERIFIABLE_METHOD | UNVERIFIABLE_METHOD


# A frozen set of values representing app notification sending providers.
APP_PROVIDER = frozenset()
# APP_PROVIDER = frozenset((
#    "app",
# ))

# A frozen set of values representing pager notification sending providers.
PAGER_PROVIDER = frozenset(("modica",))

# A frozen set of values representing SMS notification sending providers.
SMS_PROVIDER = frozenset(("modica", "twilio"))

# A frozen set of values representing Pushover notification sending providers.
PUSHOVER_PROVIDER = frozenset(("pushover",))

# A frozen set of values representing all possible sending providers for a notification.
PROVIDER = APP_PROVIDER | PAGER_PROVIDER | SMS_PROVIDER | PUSHOVER_PROVIDER

# A MappingProxyType (immutable rendering of a dict) object providing a mapping
# of possible sending providers for each method.
PROVIDER_FOR_METHOD = types.MappingProxyType(
    {
        "sms": SMS_PROVIDER,
        "pager": PAGER_PROVIDER,
        "app": APP_PROVIDER,
        "pushover": PUSHOVER_PROVIDER,
    }
)

hotpotato/notifications/queue/__init__.py
"""
Notification message queue functions.
"""


from hotpotato.notifications.queue.brokers import rabbitmq, stub


def init_app(app):
    """
    Initialise the notification message queue.
    """

    with app.app_context():
        test = False  # TODO: Incorporate FLASK_TESTING into this.
        if test:
            stub.init()
        else:
            rabbitmq.init()

hotpotato/notifications/senders/__init__.py
"""
Notification sender constants and helper classes.
"""


from flask import current_app

from hotpotato.notifications.senders import (
    pager_modica,
    pushover,
    sms_modica,
    sms_twilio,
)
from hotpotato.notifications.senders.debug_sender import DebugSender

APP = tuple()
# APP = ( # TODO: Hot Potato app
#    app.AppSender(),
# )

PUSHOVER = tuple((pushover.PushoverSender(),))

PAGER = tuple((pager_modica.ModicaPagerSender(),))

SMS = tuple((sms_modica.ModicaSMSSender(), sms_twilio.TwilioSMSSender()))

ALL = APP + PUSHOVER + PAGER + SMS


def for_method(method):
    """
    Return the possible senders for the given method.
    """

    if current_app.config["TESTING"]:
        return tuple((DebugSender(method),))
    else:
        if method == "app":
            return APP
        elif method == "pushover":
            return PUSHOVER
        elif method == "pager":
            return PAGER
        elif method == "sms":
            return SMS
        else:
            raise ValueError(method)

hotpotato/views/notifications/__init__.py
from hotpotato.views.notifications import views
from hotpotato.views.notifications._blueprint import blueprint

__all__ = ["views", "blueprint"]

hotpotato/views/notifications/_blueprint.py
"""
Notification views blueprint.
"""


import flask

blueprint = flask.Blueprint("views_notifications", __name__)

hotpotato/views/notifications/views.py
from http import HTTPStatus as Status

from flask import abort, flash, redirect, render_template, request, url_for

from hotpotato.models import db
from hotpotato.notifications import (
    exceptions as notifications_exceptions,
    notifications,
)
from hotpotato.permissions import login_required
from hotpotato.views.notifications import functions
from hotpotato.views.notifications._blueprint import blueprint
from hotpotato.views.notifications.forms import AcknowledgeForm


@blueprint.route("/", methods=["GET"])
@login_required
def notifications_get():
    """
    Display all notifications.
    """

    return functions.render_notifications_page()


@blueprint.route("/<notif_id>", methods=["GET"])
@login_required
def notifications_get_by_id(notif_id):
    """
    Display information about a specific notifications.
    """

    form = AcknowledgeForm()

    try:
        return render_template(
            "notifications/get_by_id.html",
            notif=notifications.get(notif_id, eager=True),
            form=form,
        )

    except notifications_exceptions.NotificationIDError:
        return abort(Status.NOT_FOUND)


@blueprint.route("/acknowledge/<notif_id>", methods=["POST"])
def acknowledge(notif_id):
    try:
        notif = notifications.get(notif_id)
    except notifications.exceptions.NotificationIDError:
        return abort(Status.NOT_FOUND)

    if notif.json["status"] != "SEND_FAILED":
        return abort(Status.BAD_REQUEST)

    notif.json["status"] = "SEND_FAILED_ACKNOWLEDGED"
    db.session.commit()

    flash("Notification acknowledged")

    return redirect(
        request.referrer
        or url_for("views_notifications.notifications_get", **request.args)
    )

hotpotato/templates/notifications/display.html.j2
{% macro display_notifications(notifications, acknowledge_form) %}
  {% set ns = namespace(date=None) %}
  {% for notif in notifications %}
    {% set notif_date = to_local_time(notif.Notification.received_dt, tz=current_user.timezone, format_='%A, %d %b %Y') %}
    {% if notif_date != ns.date %}
      {% if ns.date %}
        {# Close the previous 'notif-group' tag #}
        </div>
      {% endif %}
      <div class="container notif-group">
        <div class="date">{{ notif_date }}</div>
      {% set ns.date = notif_date %}
    {% endif %}
    <div class="card-wrapper">
      {% if notif.Notification.notif_type == "alert" %}
      <a class="server-link" href="{{ notif.Server.link }}"><img class="icon" src="{{ url_for('static', filename='img/icons/icon-external-link.svg') }}" alt=""></a>
      {% endif %}
      <a class="dropdown-toggle btn-icon no-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="icon" src="{{ url_for('static', filename='img/icons/icon-more.svg') }}" alt=""></a>
      <div class="dropdown-menu dropdown-menu-right dropdown-action" aria-labelledby="navbarDropdown">
        <a
          class="dropdown-item"
          href="{{ url_for('views_notifications.notifications_get_by_id', notif_id=notif.Notification.id) }}">
          Details
        </a>
        <button
          type="button"
          class="dropdown-item link-copy"
          data-clipboard-text="{{ request.url_root }}{{ url_for('views_notifications.notifications_get_by_id', notif_id=notif.Notification.id)[1:] }}">
          Copy link
        </a>
        <button
          type="button"
          class="dropdown-item link-copy"
          data-clipboard-text="{{ notif.Notification.body }}">
          Copy summary
        </button>
        {% if notif.Notification.json['status'] == 'SEND_FAILED' %}
          <form
            action="{{url_for('views_notifications.acknowledge',
            notif_id=notif.Notification.id, **request.args)}}"
            method="POST">
            {{acknowledge_form.csrf_token}}
            <button class="text-danger dropdown-item">Acknowledge</button>
          </form>
        {% endif %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" data-toggle="collapse" href="#collapse{{ notif.Notification.id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
          Show raw data
        </a>
      </div>
      <div class="card{% if notif.Notification.is_critical or notif.Notification.failed_to_send() %} fire{% endif %}">
        {{ render_notification_icon(notif.Notification) }}
        {{ render_notification_card(notif) }}
        </div>
      </a>
    </div>
  {% endfor %}

  {% if ns.date %}
    {# Close the previous 'notif-group' tag #}
    </div>
  {% endif %}
{% endmacro %}

{% macro render_notification_icon(notif, link=True) %}
  {% if notif.notif_type == "alert" %}
    {% if notif.is_critical %}
      {% set title = "Critical Alert" %}
      {% set icon = url_for('static', filename='img/icons/icon-fire.svg') %}
    {% elif notif.json["state"] == "WARNING" %}
      {% set title = "Warning" %}
      {% set icon = url_for('static', filename='img/icons/icon-alert.svg') %}
    {% elif notif.json["state"] == "UP" or notif.json["state"] == "OK" %}
      {% set title = "Status update" %}
      {% set icon = url_for('static', filename='img/icons/icon-thumb-up.svg') %}
    {% else %}
      {% set title = "Alert" %}
      {% set icon = url_for('static', filename='img/icons/icon-alert.svg') %}
    {% endif %}
  {% elif notif.notif_type == "handover" %}
    {% set title = "Handover" %}
    {% set icon = url_for('static', filename='img/icons/icon-next.svg') %}
  {% elif notif.notif_type == "message" %}
    {% set title = "Message" %}
    {% set icon = url_for('static', filename='img/icons/icon-message.svg') %}
  {% else %}
    {% set title = "Notification" %}
    {% set icon = url_for('static', filename='img/icons/icon-message.svg') %}
  {% endif %}
  {% if link %}
  <a href="{{ url_for('views_notifications.notifications_get_by_id',
  notif_id=notif.id) }}" class="card-icon" data-toggle="tooltip"
  data-placement="top" title="{{ title }}">
  {% endif %}
    <img class="icon" src="{{ icon }}" alt="{{ title }}">
  {% if link %}
  </a>
  {% endif %}
{% endmacro %}

{% macro render_notification_title(notif) %}
  {% if notif.Notification.notif_type == "alert" %}
    {% if notif.Notification.json["service_name"] %}
      <span class="service">{{ notif.Notification.json["service_name"] }}</span>
      <span class="text-subtle"> on </span>
    {% endif %}
    <span class="hostname"{% if notif.Notification.json["display_name"] %} data-toggle="tooltip" data-placement="top" title="{{ notif.Notification.json["display_name"] }}"{% endif %}>
      {{ notif.Notification.json["hostname"] }}
    </span>
  {% elif notif.Notification.notif_type == "handover" %}
    {%- set to_user = notif.to_user -%}
    {%- set from_user = notif.from_user -%}
    <span class="tater-holder">{{ render_user(to_user, link=False) }}{% if to_user.id == notif.user_id %}<small>(recipient)</small>{% endif %}</span>
    {% if from_user %}
      <span class="text-subtle">has taken over the pager from</span>
      <span class="tater-giver">{{ render_user(from_user, link=False) }}{% if from_user.id == notif.user_id %}<small>(recipient)</small>{% endif %}</span>
    {% else %}
      <span class="text-subtle">has taken the pager</span>
    {% endif %}
  {% elif notif.Notification.notif_type == "message" %}
    {%- set from_user = notif.from_user -%}
    {% if from_user %}
      {{ render_user(from_user, link=False) }}
    {% else %}
      Hot Potato
      <span class="badge badge-secondary font-weight-normal">internal</span>
    {% endif %}
  {% else %}
  {% endif %}
  {% if notif.Notification.json["trouble_code"] and config.get('HOTPOTATO_TROUBLECODE_URL') -%}
    &mdash; <a href="{{ config.get('HOTPOTATO_TROUBLECODE_URL').format(trouble_code=notif.Notification.json['trouble_code']) }}">{{ notif.Notification.json["trouble_code"] }}</a>
  {%- endif -%}
{% endmacro %}

{% macro render_notification_card(notif) %}
  {% set notif_time = to_local_time(notif.Notification.received_dt, tz=current_user.timezone, format_='%Y-%m-%d %I:%M %p') %}
  {% set notif_dt = to_local_time(notif.Notification.received_dt, tz=current_user.timezone, format_='%Y-%m-%d&nbsp;%H:%M:%S %z') %}
  <div class="card-body">
    <div class="card-title">
      <h2 class="h6">{{render_notification_title(notif)}}</h2>
    </div>
    <div class="card-text">
      <div>
        <span class="time" data-toggle="tooltip" title="{{ notif_dt }}">{{ notif_time }}</span>
        <span class="message">
          {% set truncate_len = 500 %}
          {% set elipsis = render_elipsis(link=url_for('views_notifications.notifications_get_by_id', notif_id=notif.Notification.id)) %}
          {% if notif.Notification.notif_type == "alert" %}
            {% set hyphen = joiner(" &mdash; ") %}
            {% if notif.Notification.json['state'] %}
              {{ hyphen() }}
              <span data-toggle="tooltip" title="Status">{{ notif.Notification.json['state'] }}</span>
            {% endif %}
            {% if notif.Notification.json['output'] %}
              {{ hyphen() }}
              <span class="message">{{ notif.Notification.json['output']|truncate(truncate_len, end=elipsis) }}</span>
            {% endif %}
          {% elif notif.Notification.notif_type in ["handover", "message"] %}
            {% if notif.Notification.json['message'] %}
              {{ notif.Notification.json['message']|truncate(truncate_len, end=elipsis) }}
            {% else %}
              <i>(No message)</i>
            {% endif %}
          {% else %}
            {{ notif.Notification.body|truncate(truncate_len, end=elipsis) }}
          {% endif %}
        </span>
      </div>
      <div class="delivery">
        {{render_status(notif.Notification)}}
      </div>
    </div>
    <div class="accordion" id="accordionExample">
      <div class="collapse" id="collapse{{ notif.id }}">
        <hr />
        <code><pre class="mb-0">{{ notif.Notification.as_json(indent=2) }}</pre></code>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro render_notification_details(notif) %}
  <table class="table">
    <tbody>
      {% if notif.notif_type == "alert" %}
        <tr>
          <th>State</th>
          <td>{{notif.json["state"]}}</td>
        </tr>
        {% if notif.json["alert_type"] == "service" %}
          <tr>
            <th>Service</th>
            <td>{{notif.json["service_name"]}}</td>
          </tr>
        {% endif %}
        <tr>
          <th>Host</th>
          <td>{{notif.json["hostname"]}}</td>
        </tr>
        <tr>
          <th>Source</th>
          <td>{{notif.Server.hostname}}</td>
        </tr>
        <tr>
          <th>Server time</th>
          <td>
            {{to_local_time(
              util.datetime_get_from_string(
                notif.Notification.json["timestamp"]
              ),
              tz=current_user.timezone
            )}}
          </td>
        </tr>
        <tr>
          <th>Output</th>
          <td>
            <textarea disabled class="form-control
            notif-message expanded">{{notif.Notification.json["output"]}}</textarea>
          </td>
        </tr>
      {% endif %}
      {% if "from_user_id" in notif.Notification.json and notif.Notification.json["from_user_id"] != None %}
        <tr>
          <th>From</th>
          <td>{{render_user(notif.from_user)}}</td>
        </tr>
      {% endif %}
      {% if "to_user_id" in notif.Notification.json and notif.Notification.json["to_user_id"] != None %}
        <tr>
          <th>To</th>
          <td>{{render_user(notif.to_user)}}</td>
        </tr>
      {% endif %}
      {% if notif.Notification.json["message"] %}
          <tr>
            <th>Message</th>
            <td><textarea disabled class="form-control notif-message expanded">{{notif.Notification.json["message"]}}</textarea></td>
          </tr>
      {% endif %}
    </tbody>
  </table>
{% endmacro %}

{% macro render_status(notif) %}
  {% if notif.has_been_received_by_client() %}
    Received by client
  {% elif notif.has_been_sent() %}
    Sent
  {% elif notif.is_sending() %}
    Sending
  {% elif notif.failed_to_send() %}
    Send failed
    {% if notif.send_failed_acknowledged() %}
      (Acknowledged)
    {% endif %}
  {% else %}
    Not yet sent
  {% endif %}
{% endmacro %}

{% macro render_user(user, link=False) %}
  {% if link %}
    <a href="#">
  {% endif %}
  {{ user.name }}
  {% if link %}
    </a>
  {% endif %}
{% endmacro %}

{% macro render_elipsis(link=False) -%}
  {% if link %}
    <a href="{{ link }}">
  {% endif %}
  &hellip;
  {% if link %}
    </a>
  {% endif -%}
{%- endmacro %}

hotpotato/templates/notifications/get.html
{% include "header.html" %}
{% include "menu.html" %}
{% include "failed_alerts.html" %}

{% block body %}

{% include "modals/message.html" %}
{% include "modals/take.html" %}

<div class="header">
{% include "messages.html" %}
  <div class="container">
    <div class="page-title">
      <h1 class="h4">{{ heading }}</h1>
      {% if i_can_figure_out_this_condition %}
      <div class="page-title-meta">
        <img class="icon" src="{{ url_for('static', filename='img/icons/icon-fire.svg') }}" alt="">
        <p>1 critical notification in last hour</p>
      </div>
      {% endif %}
    </div>
    <div id="notif-actions" class="actions"> <!-- Actions menu -->
      <div class="assigned mr-auto">
        {% if not pagerperson.id %}
          The tater isn't held!
        {% elif pagerperson == current_user %}
          <div class="assignee">You</div> hold the tater
        {% else %}
          <div class="assignee">{{ pagerperson.name }}</div> holds the tater
        {% endif %}
      </div>
      {% if pagerperson.id %}
        <div data-toggle="tooltip" data-placement="bottom" title="Message tater holder">
          <button id="message-tater-button" type="button" class="btn btn-lg btn-icon btn-outline-secondary" data-toggle="modal" data-target="#message-tater">
            <img class="icon" src="{{ url_for('static', filename='img/icons/icon-message-add.svg') }}" alt="">
          </button>
        </div>
      {% endif %}
      <button {% if pagerperson == current_user %}disabled {% endif %}type="button" class="btn btn-lg btn-primary btn-tater" data-toggle="modal" data-target="#take-tater">
        Take Tater
        <svg>
          <path id="btn-tater" d="M62.05 56C43.967 56 25.883 56 7.8 56C3.5 56 0 52.5 0 48.3C0 37.433 0 26.567 0 15.7C0 11.5 3.5 8 7.8 8C16.4 8 25 8 33.6 8C42.2 8 50.8 8 59.4 8C78.333 8 97.267 8 116.2 8C116.2 8 116.2 8 116.2 8C120.5 8 124 11.5 124.1 15.7C124.1 26.533 124.1 37.367 124.1 48.2C124.1 52.5 120.6 56 116.3 56C107.258 56 98.217 56 89.175 56L62.05 56"/>
        </svg>
      </button>
    </div>
  </div>
</div>

<!-- Notification search filter -->
<!-- Filter mobile accordion toggle -->

<div class="container filter-toggle">
  <button class="btn btn-sm btn-outline-secondary btn-block" type="button" data-target=".filters" data-toggle="collapse" >Filter notifications</button>
</div>

<div id="notif-filters" class="filters collapse">
    <div class="container flex-wrap">
      <form method="get" class="form-inline flex-sm-grow-1" id="notification-filter-form">
        <input type="hidden" name="team_id" value="{{current_team.id}}">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><img class="icon icon-secondary" src="{{ url_for('static', filename='img/icons/icon-search.svg') }}" alt=""></span>
          </div>
          <input type="text" name="body" {% if 'body' in current_search_filters %}value="{{ current_search_filters['body'] }}" {% endif %}class="form-control" placeholder="Filter..." aria-label="Filter notifications" />
        </div>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><img class="icon icon-secondary" src="{{ url_for('static', filename='img/icons/icon-calendar.svg') }}" alt=""></span>
          </div>
          <input type="date" {% if 'start_date' in current_search_filters %}value="{{ current_search_filters['start_date'] }}" {% endif %}name="start_date" class="form-control" placeholder="dd/mm/yyyy" aria-label="Filter notifications" />
        </div>
        <div class="input-group input-range">
          <input type="date" {% if 'end_date' in current_search_filters %}value="{{ current_search_filters['end_date'] }}" {% endif %}name="end_date" class="form-control" placeholder="dd/mm/yyyy" aria-label="Filter notifications" />
        </div>
        <select
          name="status"
          class="form-control">
          <option value="">Any</option>
          {% for status in notifications.STATUS %}
            <option
            value="{{status}}"
            {% if 'status' in current_search_filters and
            current_search_filters['status'] == status %}
            selected
            {% endif %}
            >{{snake_to_sentence(status)}}</option>
          {% endfor %}
        </select>
        <div class="input-group">
          <button id="search-filters-apply" type="submit" class="btn btn-primary">Apply</button>
        </div>
      </form>
      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {% for id in id_notif|map(attribute='id') -%}
          <input type="hidden" name="id" value="{{ id }}">
        {%- endfor %}
        <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Export <span class="caret"></span></button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
          <button type="submit" formaction="{{ url_for('api_web_v1.notifications_get') }}" class="dropdown-item" id="notifications-export-as-json">As JSON</button>
          <button type="submit" formaction="{{ url_for('api_web_v1.notifications_get_as_csv') }}" class="dropdown-item" id="notifications-export-as-csv">As CSV</button>
        </div>
      </form>
    </div>
</div>

<!-- Notifications table -->

<div id="notifications">
  {% from "notifications/display.html.j2" import display_notifications %}
  {{ display_notifications(id_notif, acknowledge_form) }}
</div>


{% endblock %}

{% include "footer.html" %}

hotpotato/templates/notifications/get_by_id.html
{% include "header.html" %}
{% include "menu.html" %}
{% include "messages.html" %}
{% include "failed_alerts.html" %}

{% import "notifications/display.html.j2" as display %}

{% block body %}

<div id="notif-details-header" class="header">
  <div class="container">
    <div class="page-title">
      <h1 class="h5">{{display.render_notification_title(notif)}}</h1>
      <div class="page-title-meta">
        {{display.render_notification_icon(notif, link=False)}}
        <p>{{to_local_time(notif.Notification.received_dt, tz=current_user.timezone,
        format_='%I:%M:%S %p, %A %x')}}</p>
      </div>
    </div>
  </div>
</div>


<div id="notif-details" class="container">
  <div class="card-wrapper">
    {% if notif.Notification.json['status'] == 'SEND_FAILED' %}
    <a
      class="dropdown-toggle btn-icon no-toggle"
      href="#"
      role="button"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false">
      <img
        class="icon"
        src="{{ url_for('static', filename='img/icons/icon-more.svg') }}"
        alt="">
    </a>
    <div
      class="dropdown-menu dropdown-menu-right dropdown-action"
      aria-labelledby="navbarDropdown">
      <form
        action="{{url_for('views_notifications.acknowledge',
        notif_id=notif.id, **request.args)}}"
        method="POST">
        {{form.csrf_token}}
        <button class="text-danger dropdown-item">Acknowledge</button>
      </form>
    </div>
    {% endif %}

    <div class="card">
        <div class="row">
          <div class="col-md-7">
            <h2 class="h6">Notification details</h6>
            <hr/>
            {{display.render_notification_details(notif)}}
          </div>
          <div class="col-md-5">
            <h2 class="h6">Delivery details</h6>
            <hr/>
            <table class="table">
              <tbody>
                <tr>
                  <th>Service</th>
                  <td>{{notif.Notification.json["provider"]}}</td>
                </tr>
                <tr>
                  <th>Status</th>
                  <td>{{display.render_status(notif.Notification)}}</td>
                </tr>
                <tr>
                  <th>Sent to</th>
                  <td>{{notif.Notification.user.name}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <span>Hot Potato ID: {{notif.id}}</span>
          {% if notif.Notification.json["node_name"] %}
            <span>Node name: {{notif.Notification.json["node_name"]}}</span>
          {% endif %}
          {% if notif.Notification.json["provider"] and notif.Notification.json["provider_notif_id"] %}
            <span>
              {{notif.Notification.json["provider"]}} ID: {{notif.Notification.json["provider_notif_id"]}}
            </span>
          {% endif %}
        </div>
    </div>
  </div>
</div>

{% endblock %}

{% include "footer.html" %}